import type { MovementRules } from "@/features/variants/common/types/movementRules";

const defaultMovementRules: Record<string, MovementRules> = {
	whitePawnForward: {
		forMovement: true,
		forCapture: false,
		conditions: [],
		validMove: true,
		moveDefinition: {
			moveX: 0,
			moveY: 1,
			range: 1,
			moveStopConditions: ["inside_piece"],
		},
	},
	whitePawnDoubleStep: {
		forMovement: true,
		forCapture: false,
		conditions: ["has_not_moved"],
		validMove: true,
		moveDefinition: {
			moveX: 0,
			moveY: 1,
			range: 1,
			moveStopConditions: [],
		},
	},
	whitePawnCaptureEast: {
		forMovement: false,
		forCapture: true,
		conditions: [],
		validMove: true,
		moveDefinition: {
			moveX: 1,
			moveY: 1,
			range: 1,
			moveStopConditions: [],
		},
	},
	whitePawnCaptureWest: {
		forMovement: false,
		forCapture: true,
		conditions: [],
		validMove: true,
		moveDefinition: {
			moveX: -1,
			moveY: 1,
			range: 1,
			moveStopConditions: [],
		},
	},
	blackPawnForward: {
		forMovement: true,
		forCapture: false,
		conditions: [],
		validMove: true,
		moveDefinition: {
			moveX: 0,
			moveY: -1,
			range: 1,
			moveStopConditions: ["inside_piece"],
		},
	},
	blackPawnDoubleStep: {
		forMovement: true,
		forCapture: false,
		conditions: ["has_not_moved"],
		validMove: true,
		moveDefinition: {
			moveX: 0,
			moveY: -1,
			range: 1,
			moveStopConditions: [],
		},
	},
	blackPawnCaptureEast: {
		forMovement: false,
		forCapture: true,
		conditions: [],
		validMove: true,
		moveDefinition: {
			moveX: 1,
			moveY: -1,
			range: 1,
			moveStopConditions: [],
		},
	},
	blackPawnCaptureWest: {
		forMovement: false,
		forCapture: true,
		conditions: [],
		validMove: true,
		moveDefinition: {
			moveX: -1,
			moveY: -1,
			range: 1,
			moveStopConditions: [],
		},
	},
	east: {
		forMovement: true,
		forCapture: true,
		conditions: [],
		validMove: true,
		moveDefinition: {
			moveX: 1,
			moveY: 0,
			range: "inf",
			moveStopConditions: ["inside_piece"],
		},
	},
	west: {
		forMovement: true,
		forCapture: true,
		conditions: [],
		validMove: true,
		moveDefinition: {
			moveX: -1,
			moveY: 0,
			range: "inf",
			moveStopConditions: ["inside_piece"],
		},
	},
	north: {
		forMovement: true,
		forCapture: true,
		conditions: [],
		validMove: true,
		moveDefinition: {
			moveX: 0,
			moveY: 1,
			range: "inf",
			moveStopConditions: ["inside_piece"],
		},
	},
	south: {
		forMovement: true,
		forCapture: true,
		conditions: [],
		validMove: true,
		moveDefinition: {
			moveX: 0,
			moveY: -1,
			range: "inf",
			moveStopConditions: ["inside_piece"],
		},
	},
	northeast: {
		forMovement: true,
		forCapture: true,
		conditions: [],
		validMove: true,
		moveDefinition: {
			moveX: 1,
			moveY: 1,
			range: "inf",
			moveStopConditions: ["inside_piece"],
		},
	},
	southwest: {
		forMovement: true,
		forCapture: true,
		conditions: [],
		validMove: true,
		moveDefinition: {
			moveX: -1,
			moveY: -1,
			range: "inf",
			moveStopConditions: ["inside_piece"],
		},
	},
	southeast: {
		forMovement: true,
		forCapture: true,
		conditions: [],
		validMove: true,
		moveDefinition: {
			moveX: 1,
			moveY: -1,
			range: "inf",
			moveStopConditions: ["inside_piece"],
		},
	},
	northwest: {
		forMovement: true,
		forCapture: true,
		conditions: [],
		validMove: true,
		moveDefinition: {
			moveX: -1,
			moveY: 1,
			range: "inf",
			moveStopConditions: ["inside_piece"],
		},
	},
	knight0201: {
		forMovement: true,
		forCapture: true,
		conditions: [],
		validMove: true,
		moveDefinition: {
			moveX: 2,
			moveY: 1,
			range: 1,
			moveStopConditions: [],
		},
	},
	knight02m1: {
		forMovement: true,
		forCapture: true,
		conditions: [],
		validMove: true,
		moveDefinition: {
			moveX: 2,
			moveY: -1,
			range: 1,
			moveStopConditions: [],
		},
	},
	knightM201: {
		forMovement: true,
		forCapture: true,
		conditions: [],
		validMove: true,
		moveDefinition: {
			moveX: -2,
			moveY: 1,
			range: 1,
			moveStopConditions: [],
		},
	},
	knightM2m1: {
		forMovement: true,
		forCapture: true,
		conditions: [],
		validMove: true,
		moveDefinition: {
			moveX: -2,
			moveY: -1,
			range: 1,
			moveStopConditions: [],
		},
	},
	knight0102: {
		forMovement: true,
		forCapture: true,
		conditions: [],
		validMove: true,
		moveDefinition: {
			moveX: 1,
			moveY: 2,
			range: 1,
			moveStopConditions: [],
		},
	},
	knightM102: {
		forMovement: true,
		forCapture: true,
		conditions: [],
		validMove: true,
		moveDefinition: {
			moveX: -1,
			moveY: 2,
			range: 1,
			moveStopConditions: [],
		},
	},
	knight01m2: {
		forMovement: true,
		forCapture: true,
		conditions: [],
		validMove: true,
		moveDefinition: {
			moveX: 1,
			moveY: -2,
			range: 1,
			moveStopConditions: [],
		},
	},
	knightM1m2: {
		forMovement: true,
		forCapture: true,
		conditions: [],
		validMove: true,
		moveDefinition: {
			moveX: -1,
			moveY: -2,
			range: 1,
			moveStopConditions: [],
		},
	},
	east1: {
		forMovement: true,
		forCapture: true,
		conditions: [],
		validMove: true,
		moveDefinition: {
			moveX: 1,
			moveY: 0,
			range: 1,
			moveStopConditions: ["inside_piece"],
		},
	},
	west1: {
		forMovement: true,
		forCapture: true,
		conditions: [],
		validMove: true,
		moveDefinition: {
			moveX: -1,
			moveY: 0,
			range: 1,
			moveStopConditions: ["inside_piece"],
		},
	},
	north1: {
		forMovement: true,
		forCapture: true,
		conditions: [],
		validMove: true,
		moveDefinition: {
			moveX: 0,
			moveY: 1,
			range: 1,
			moveStopConditions: ["inside_piece"],
		},
	},
	south1: {
		forMovement: true,
		forCapture: true,
		conditions: [],
		validMove: true,
		moveDefinition: {
			moveX: 0,
			moveY: -1,
			range: 1,
			moveStopConditions: ["inside_piece"],
		},
	},
	northeast1: {
		forMovement: true,
		forCapture: true,
		conditions: [],
		validMove: true,
		moveDefinition: {
			moveX: 1,
			moveY: 1,
			range: 1,
			moveStopConditions: ["inside_piece"],
		},
	},
	southwest1: {
		forMovement: true,
		forCapture: true,
		conditions: [],
		validMove: true,
		moveDefinition: {
			moveX: -1,
			moveY: -1,
			range: 1,
			moveStopConditions: ["inside_piece"],
		},
	},
	southeast1: {
		forMovement: true,
		forCapture: true,
		conditions: [],
		validMove: true,
		moveDefinition: {
			moveX: 1,
			moveY: -1,
			range: 1,
			moveStopConditions: ["inside_piece"],
		},
	},
	northwest1: {
		forMovement: true,
		forCapture: true,
		conditions: [],
		validMove: true,
		moveDefinition: {
			moveX: -1,
			moveY: 1,
			range: 1,
			moveStopConditions: ["inside_piece"],
		},
	},
};

export { defaultMovementRules };
