import type {
	PieceRules,
	PiecesRules,
} from "@/features/variants/common/types/pieceRules";

const queenRules: PieceRules = {
	moves: [
		{
			forMovement: true,
			forCapture: true,
			conditions: [],
			validMove: true,
			moveDefinition: {
				moveX: 1,
				moveY: 0,
				range: "inf",
				moveStopConditions: ["inside_piece"],
			},
			chainedMoves: [],
		},
		{
			forMovement: true,
			forCapture: true,
			conditions: [],
			validMove: true,
			moveDefinition: {
				moveX: -1,
				moveY: 0,
				range: "inf",
				moveStopConditions: ["inside_piece"],
			},
			chainedMoves: [],
		},
		{
			forMovement: true,
			forCapture: true,
			conditions: [],
			validMove: true,
			moveDefinition: {
				moveX: 0,
				moveY: 1,
				range: "inf",
				moveStopConditions: ["inside_piece"],
			},
			chainedMoves: [],
		},
		{
			forMovement: true,
			forCapture: true,
			conditions: [],
			validMove: true,
			moveDefinition: {
				moveX: 0,
				moveY: -1,
				range: "inf",
				moveStopConditions: ["inside_piece"],
			},
			chainedMoves: [],
		},
		{
			forMovement: true,
			forCapture: true,
			conditions: [],
			validMove: true,
			moveDefinition: {
				moveX: 1,
				moveY: 1,
				range: "inf",
				moveStopConditions: ["inside_piece"],
			},
			chainedMoves: [],
		},
		{
			forMovement: true,
			forCapture: true,
			conditions: [],
			validMove: true,
			moveDefinition: {
				moveX: -1,
				moveY: -1,
				range: "inf",
				moveStopConditions: ["inside_piece"],
			},
			chainedMoves: [],
		},
		{
			forMovement: true,
			forCapture: true,
			conditions: [],
			validMove: true,
			moveDefinition: {
				moveX: 1,
				moveY: -1,
				range: "inf",
				moveStopConditions: ["inside_piece"],
			},
			chainedMoves: [],
		},
		{
			forMovement: true,
			forCapture: true,
			conditions: [],
			validMove: true,
			moveDefinition: {
				moveX: -1,
				moveY: 1,
				range: "inf",
				moveStopConditions: ["inside_piece"],
			},
			chainedMoves: [],
		},
	],
};

const rookRules: PieceRules = {
	moves: [
		{
			forMovement: true,
			forCapture: true,
			conditions: [],
			validMove: true,
			moveDefinition: {
				moveX: 1,
				moveY: 0,
				range: "inf",
				moveStopConditions: ["inside_piece"],
			},
			chainedMoves: [],
		},
		{
			forMovement: true,
			forCapture: true,
			conditions: [],
			validMove: true,
			moveDefinition: {
				moveX: -1,
				moveY: 0,
				range: "inf",
				moveStopConditions: ["inside_piece"],
			},
			chainedMoves: [],
		},
		{
			forMovement: true,
			forCapture: true,
			conditions: [],
			validMove: true,
			moveDefinition: {
				moveX: 0,
				moveY: 1,
				range: "inf",
				moveStopConditions: ["inside_piece"],
			},
			chainedMoves: [],
		},
		{
			forMovement: true,
			forCapture: true,
			conditions: [],
			validMove: true,
			moveDefinition: {
				moveX: 0,
				moveY: -1,
				range: "inf",
				moveStopConditions: ["inside_piece"],
			},
			chainedMoves: [],
		},
	],
};
const bishopRules: PieceRules = {
	moves: [
		{
			forMovement: true,
			forCapture: true,
			conditions: [],
			validMove: true,
			moveDefinition: {
				moveX: 1,
				moveY: 1,
				range: "inf",
				moveStopConditions: ["inside_piece"],
			},
			chainedMoves: [],
		},
		{
			forMovement: true,
			forCapture: true,
			conditions: [],
			validMove: true,
			moveDefinition: {
				moveX: -1,
				moveY: -1,
				range: "inf",
				moveStopConditions: ["inside_piece"],
			},
			chainedMoves: [],
		},
		{
			forMovement: true,
			forCapture: true,
			conditions: [],
			validMove: true,
			moveDefinition: {
				moveX: 1,
				moveY: -1,
				range: "inf",
				moveStopConditions: ["inside_piece"],
			},
			chainedMoves: [],
		},
		{
			forMovement: true,
			forCapture: true,
			conditions: [],
			validMove: true,
			moveDefinition: {
				moveX: -1,
				moveY: 1,
				range: "inf",
				moveStopConditions: ["inside_piece"],
			},
			chainedMoves: [],
		},
	],
};
const knightRules = {
	moves: [
		{
			forMovement: true,
			forCapture: true,
			conditions: [],
			validMove: true,
			moveDefinition: {
				moveX: 2,
				moveY: 1,
				range: 1,
				moveStopConditions: [],
			},
			chainedMoves: [],
		},
		{
			forMovement: true,
			forCapture: true,
			conditions: [],
			validMove: true,
			moveDefinition: {
				moveX: 2,
				moveY: -1,
				range: 1,
				moveStopConditions: [],
			},
			chainedMoves: [],
		},
		{
			forMovement: true,
			forCapture: true,
			conditions: [],
			validMove: true,
			moveDefinition: {
				moveX: -2,
				moveY: 1,
				range: 1,
				moveStopConditions: [],
			},
			chainedMoves: [],
		},
		{
			forMovement: true,
			forCapture: true,
			conditions: [],
			validMove: true,
			moveDefinition: {
				moveX: -2,
				moveY: -1,
				range: 1,
				moveStopConditions: [],
			},
			chainedMoves: [],
		},
		{
			forMovement: true,
			forCapture: true,
			conditions: [],
			validMove: true,
			moveDefinition: {
				moveX: 1,
				moveY: 2,
				range: 1,
				moveStopConditions: [],
			},
			chainedMoves: [],
		},
		{
			forMovement: true,
			forCapture: true,
			conditions: [],
			validMove: true,
			moveDefinition: {
				moveX: -1,
				moveY: 2,
				range: 1,
				moveStopConditions: [],
			},
			chainedMoves: [],
		},
		{
			forMovement: true,
			forCapture: true,
			conditions: [],
			validMove: true,
			moveDefinition: {
				moveX: 1,
				moveY: -2,
				range: 1,
				moveStopConditions: [],
			},
			chainedMoves: [],
		},
		{
			forMovement: true,
			forCapture: true,
			conditions: [],
			validMove: true,
			moveDefinition: {
				moveX: -1,
				moveY: -2,
				range: 1,
				moveStopConditions: [],
			},
			chainedMoves: [],
		},
	],
};
const kingRules = {
	moves: [
		{
			forMovement: true,
			forCapture: true,
			conditions: [],
			validMove: true,
			moveDefinition: {
				moveX: 1,
				moveY: 0,
				range: 1,
				moveStopConditions: [],
			},
			chainedMoves: [],
		},
		{
			forMovement: true,
			forCapture: true,
			conditions: [],
			validMove: true,
			moveDefinition: {
				moveX: -1,
				moveY: 0,
				range: 1,
				moveStopConditions: [],
			},
			chainedMoves: [],
		},
		{
			forMovement: true,
			forCapture: true,
			conditions: [],
			validMove: true,
			moveDefinition: {
				moveX: 0,
				moveY: 1,
				range: 1,
				moveStopConditions: [],
			},
			chainedMoves: [],
		},
		{
			forMovement: true,
			forCapture: true,
			conditions: [],
			validMove: true,
			moveDefinition: {
				moveX: 0,
				moveY: -1,
				range: 1,
				moveStopConditions: [],
			},
			chainedMoves: [],
		},
		{
			forMovement: true,
			forCapture: true,
			conditions: [],
			validMove: true,
			moveDefinition: {
				moveX: 1,
				moveY: 1,
				range: 1,
				moveStopConditions: [],
			},
			chainedMoves: [],
		},
		{
			forMovement: true,
			forCapture: true,
			conditions: [],
			validMove: true,
			moveDefinition: {
				moveX: -1,
				moveY: -1,
				range: 1,
				moveStopConditions: [],
			},
			chainedMoves: [],
		},
		{
			forMovement: true,
			forCapture: true,
			conditions: [],
			validMove: true,
			moveDefinition: {
				moveX: 1,
				moveY: -1,
				range: 1,
				moveStopConditions: [],
			},
			chainedMoves: [],
		},
		{
			forMovement: true,
			forCapture: true,
			conditions: [],
			validMove: true,
			moveDefinition: {
				moveX: -1,
				moveY: 1,
				range: 1,
				moveStopConditions: [],
			},
			chainedMoves: [],
		},
	],
};
const defaultPieceRules: PiecesRules = {
	whitePawn: {
		moves: [
			{
				forMovement: true,
				forCapture: false,
				conditions: [],
				validMove: true,
				moveDefinition: {
					moveX: 0,
					moveY: 1,
					range: 1,
					moveStopConditions: ["inside_piece"],
				},
				chainedMoves: [
					{
						forMovement: true,
						forCapture: false,
						conditions: ["has_not_moved"],
						validMove: true,
						moveDefinition: {
							moveX: 0,
							moveY: 1,
							range: 1,
							moveStopConditions: [],
						},
						chainedMoves: [],
					},
				],
			},
			{
				forMovement: false,
				forCapture: true,
				conditions: [],
				validMove: true,
				moveDefinition: {
					moveX: 1,
					moveY: 1,
					range: 1,
					moveStopConditions: [],
				},
				chainedMoves: [],
			},
			{
				forMovement: false,
				forCapture: true,
				conditions: [],
				validMove: true,
				moveDefinition: {
					moveX: -1,
					moveY: 1,
					range: 1,
					moveStopConditions: [],
				},
				chainedMoves: [],
			},
		],
	},

	blackPawn: {
		moves: [
			{
				forMovement: true,
				forCapture: false,
				conditions: [],
				validMove: true,
				moveDefinition: {
					moveX: 0,
					moveY: -1,
					range: 1,
					moveStopConditions: [],
				},
				chainedMoves: [
					{
						forMovement: true,
						forCapture: false,
						conditions: ["has_not_moved"],
						validMove: true,
						moveDefinition: {
							moveX: 0,
							moveY: -1,
							range: 1,
							moveStopConditions: [],
						},
						chainedMoves: [],
					},
				],
			},
			{
				forMovement: false,
				forCapture: true,
				conditions: [],
				validMove: true,
				moveDefinition: {
					moveX: 1,
					moveY: -1,
					range: 1,
					moveStopConditions: [],
				},
				chainedMoves: [],
			},
			{
				forMovement: false,
				forCapture: true,
				conditions: [],
				validMove: true,
				moveDefinition: {
					moveX: -1,
					moveY: -1,
					range: 1,
					moveStopConditions: [],
				},
				chainedMoves: [],
			},
		],
	},
	whiteQueen: queenRules,
	blackQueen: queenRules,

	whiteRook: rookRules,
	blackRook: rookRules,

	whiteBishop: bishopRules,
	blackBishop: bishopRules,

	whiteKnight: knightRules,
	blackKnight: knightRules,

	whiteKing: kingRules,
	blackKing: kingRules,
};

export { defaultPieceRules };
